version: "3.7"

services: 
    database_task: 
        image: postgres
        container_name: database_task
        restart: always
        ports: 
            - 5432:5432
        environment: 
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=task
            - POSTGRES_DB=task
        volumes: 
            - pgdata:/data/postgres
    app: 
        build: .
        container_name: taskmanagement
        ports: 
            - 3000:3000
        volumes: 
            - .:/usr/app
        links: 
            - database_task
        depends_on: 
            - database_task

volumes: 
    pgdata:
        driver: local